language: cpp
compiler:
  - gcc
  - clang

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./autogen.sh; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./configure; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make -j4; fi

notifications:
  email:
    recipients:
      - ndbrandes@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#xoreos"
    on_success: change
    on_failure: always
    use_notice: true
